#!/usr/bin/env bash
# export-for-web.sh — Export Claude Code skills as system prompts for claude.ai Projects & Claude Desktop
# Usage: ./export-for-web.sh [--skill <name>] [--all] [--list] [--output <file>]

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

# ── paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"
OUTPUT_DIR="$SCRIPT_DIR/web-prompts"

# Skills that rely on local Python scripts — not usable on web/desktop
PYTHON_SKILLS=("ui-ux-pro-max")

# ── helpers ───────────────────────────────────────────────────────────────────
strip_frontmatter() {
  local file="$1"
  # Remove YAML frontmatter (everything between first --- and second ---)
  awk 'BEGIN{fm=0} /^---$/{if(fm==0){fm=1;next}else{fm=2;next}} fm==2{print}' "$file"
}

get_skill_description() {
  local skill_dir="$1"
  local skill_file="$skill_dir/SKILL.md"
  [[ ! -f "$skill_file" ]] && echo "(no description)" && return
  # Extract description — handles both single-line and block-scalar (>) formats
  awk '
    BEGIN{fm=0; in_desc=0; block=0; result=""}
    /^---$/{fm++; next}
    fm!=1{next}
    /^description: *>/{block=1; in_desc=1; next}
    /^description:/{
      val=$0; gsub(/^description: *"?|"?[ \t]*$/, "", val)
      if(val != "" && val != ">"){result=val; in_desc=0}
      else{in_desc=1}
      next
    }
    in_desc && /^  /{
      line=$0; gsub(/^  /, "", line)
      if(result==""){result=line}else{result=result " " line}
      next
    }
    in_desc && !/^  /{in_desc=0}
    END{print substr(result,1,120)}
  ' "$skill_file"
}

is_python_skill() {
  local name="$1"
  for ps in "${PYTHON_SKILLS[@]}"; do
    [[ "$name" == "$ps" ]] && return 0
  done
  return 1
}

list_skills() {
  echo -e "\n${BOLD}Available skills:${RESET}\n"
  local i=1
  for dir in "$SKILLS_DIR"/*/; do
    local name
    name="$(basename "$dir")"
    [[ ! -f "$dir/SKILL.md" ]] && continue
    local desc
    desc="$(get_skill_description "$dir")"
    local note=""
    if is_python_skill "$name"; then
      note="${YELLOW} [requires Python — CLI only]${RESET}"
    fi
    printf "  ${CYAN}%2d${RESET}. ${BOLD}%-30s${RESET}${note}\n     %s\n\n" "$i" "$name" "$desc"
    i=$((i+1))
  done
}

export_skill() {
  local skill_name="$1"
  local skill_dir="$SKILLS_DIR/$skill_name"
  local skill_file="$skill_dir/SKILL.md"

  if [[ ! -f "$skill_file" ]]; then
    echo -e "${RED}✗ Skill '$skill_name' not found in $SKILLS_DIR${RESET}"
    return 1
  fi

  local body
  body="$(strip_frontmatter "$skill_file")"

  if is_python_skill "$skill_name"; then
    local warning="
> ⚠️  **Note:** This skill normally uses a local Python BM25 search engine to generate design systems.
> On claude.ai web and Claude Desktop, the Python scripts cannot run — Claude will use the knowledge
> embedded in this prompt instead. For full functionality, use Claude Code CLI.
"
    echo "$warning"
    echo "$body"
  else
    echo "$body"
  fi
}

build_header() {
  local skills_list="$1"
  cat <<EOF
# Claude Expert System Prompt
# Generated by claude-setup · https://github.com/thesaifalitai/claude-setup
# Skills included: $skills_list
# Platform: claude.ai Web / Claude Desktop
#
# HOW TO USE:
#   claude.ai: Open a Project → Project Settings → paste under "Project Instructions"
#   Desktop:   Open a Project → Project Settings → paste under "Project Instructions"
#   New chat:  Paste at the start of any conversation to activate these skills
#
# The skills below define Claude's expertise. Claude will automatically apply
# the right knowledge based on your questions — no need to invoke them manually.
# ─────────────────────────────────────────────────────────────────────────────

EOF
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  local mode="interactive"
  local output_file=""
  local selected_skills=()

  # Parse args
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --list|-l)        list_skills; exit 0 ;;
      --all|-a)         mode="all" ;;
      --skill|-s)       mode="single"; selected_skills+=("$2"); shift ;;
      --output|-o)      output_file="$2"; shift ;;
      --help|-h)
        echo "Usage: $0 [--skill <name>] [--all] [--list] [--output <file>]"
        echo ""
        echo "  --list              List all available skills"
        echo "  --all               Export ALL skills into one prompt"
        echo "  --skill <name>      Export a specific skill (can repeat)"
        echo "  --output <file>     Save to file (default: web-prompts/<name>.md)"
        echo ""
        echo "Examples:"
        echo "  $0 --skill flutter-dev --skill react-native-expo"
        echo "  $0 --all --output my-team-prompt.md"
        echo "  $0 --skill uiux-design --output ~/Desktop/uiux-prompt.md"
        exit 0 ;;
      *) echo -e "${RED}Unknown option: $1${RESET}"; exit 1 ;;
    esac
    shift
  done

  # Interactive mode — show numbered menu
  if [[ "$mode" == "interactive" ]]; then
    echo -e "\n${BOLD}${BLUE}╔══════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}${BLUE}║   Export Claude Skills → Web / Desktop System Prompt ║${RESET}"
    echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════════════╝${RESET}\n"

    # Build indexed array of available skills
    local skill_names=()
    for dir in "$SKILLS_DIR"/*/; do
      local name
      name="$(basename "$dir")"
      [[ -f "$dir/SKILL.md" ]] && skill_names+=("$name")
    done

    echo -e "${BOLD}Available skills:${RESET}\n"
    local i=1
    for name in "${skill_names[@]}"; do
      local note=""
      is_python_skill "$name" && note=" ${YELLOW}[CLI only — Python scripts]${RESET}"
      printf "  ${CYAN}%2d${RESET}. %-30s%s\n" "$i" "$name" "$note"
      i=$((i+1))
    done

    echo -e "\n${BOLD}Options:${RESET}"
    echo "  • Enter numbers separated by spaces (e.g. 1 3 5)"
    echo "  • Enter skill names directly (e.g. flutter-dev react-native-expo)"
    echo "  • Type 'all' to export everything"
    echo ""
    read -rp "Your selection: " selection

    if [[ "$selection" == "all" ]]; then
      mode="all"
    else
      for token in $selection; do
        if [[ "$token" =~ ^[0-9]+$ ]]; then
          local idx=$((token - 1))
          if [[ $idx -ge 0 && $idx -lt ${#skill_names[@]} ]]; then
            selected_skills+=("${skill_names[$idx]}")
          else
            echo -e "${RED}✗ Invalid number: $token${RESET}"
            exit 1
          fi
        else
          selected_skills+=("$token")
        fi
      done
    fi
  fi

  # Collect full list for "all" mode
  if [[ "$mode" == "all" ]]; then
    selected_skills=()
    for dir in "$SKILLS_DIR"/*/; do
      local name
      name="$(basename "$dir")"
      [[ -f "$dir/SKILL.md" ]] && selected_skills+=("$name")
    done
  fi

  if [[ ${#selected_skills[@]} -eq 0 ]]; then
    echo -e "${RED}✗ No skills selected.${RESET}"
    exit 1
  fi

  # Determine output file
  if [[ -z "$output_file" ]]; then
    mkdir -p "$OUTPUT_DIR"
    if [[ ${#selected_skills[@]} -eq 1 ]]; then
      output_file="$OUTPUT_DIR/${selected_skills[0]}.md"
    else
      output_file="$OUTPUT_DIR/combined-$(date +%Y%m%d-%H%M%S).md"
    fi
  fi

  # Build the output
  local skills_label
  skills_label="$(IFS=", "; echo "${selected_skills[*]}")"

  {
    build_header "$skills_label"

    for skill_name in "${selected_skills[@]}"; do
      echo "---"
      echo ""
      echo "## Skill: $skill_name"
      echo ""
      export_skill "$skill_name"
      echo ""
    done
  } > "$output_file"

  echo -e "\n${GREEN}✓ Exported ${#selected_skills[@]} skill(s) to:${RESET}"
  echo -e "  ${BOLD}$output_file${RESET}"
  echo ""

  # Copy to clipboard if available
  if command -v pbcopy &>/dev/null; then
    pbcopy < "$output_file"
    echo -e "${GREEN}✓ Copied to clipboard (macOS)${RESET}"
  elif command -v xclip &>/dev/null; then
    xclip -selection clipboard < "$output_file"
    echo -e "${GREEN}✓ Copied to clipboard (xclip)${RESET}"
  elif command -v xsel &>/dev/null; then
    xsel --clipboard --input < "$output_file"
    echo -e "${GREEN}✓ Copied to clipboard (xsel)${RESET}"
  fi

  echo ""
  echo -e "${BOLD}Next steps:${RESET}"
  echo -e "  ${CYAN}claude.ai${RESET}  → Create/open a Project → ⚙ Settings → Project Instructions → paste"
  echo -e "  ${CYAN}Desktop ${RESET}   → Create/open a Project → ⚙ Settings → Project Instructions → paste"
  echo -e "  ${CYAN}New chat${RESET}   → Paste at the start of any conversation"
  echo ""
  echo -e "  Full guide: ${BOLD}WEB_DESKTOP_GUIDE.md${RESET}"
  echo ""
}

main "$@"
